# Generated by Django 3.2.14 on 2022-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productType', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Discount')),
            ],
        ),
    ]
