# Generated by Django 3.2.14 on 2022-07-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productss', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='doc',
            field=models.FileField(default='Doc/None/No-doc.pdf', upload_to='Doc/'),
        ),
    ]
